export const DATESCHEDULE_POST = 'DATESCHEDULE_POST';
export const DATESCHEDULE_PUT = 'DATESCHEDULE_PUT';
export const DATESCHEDULE_GET = 'DATESCHEDULE_GET';
export const DATESCHEDULE_DELETE = 'DATESCHEDULE_DELETE';
export const DATESCHEDULE_RECEIVE = 'DATESCHEDULE_RECEIVE';
