export const WEEKSCHEDULE_POST = 'WEEKSCHEDULE_POST';
export const WEEKSCHEDULE_PUT = 'WEEKSCHEDULE_PUT';
export const WEEKSCHEDULE_GET = 'WEEKSCHEDULE_GET';
export const WEEKSCHEDULE_DELETE = 'WEEKSCHEDULE_DELETE';
export const WEEKSCHEDULE_RECEIVE = 'WEEKSCHEDULE_RECEIVE';
export const WEEKSCHEDULES_RECEIVE = 'WEEKSCHEDULES_RECEIVE';